version: '3.7'

services:
    {{ cookiecutter.import_name }}:
        build: .
        env_file: .env
        environment:
            DATABASE_URL: postgres://{{ cookiecutter.import_name }}:password@db:5432/{{ cookiecutter.import_name }}
            REDIS_URL: redis://redis:6379/0
        volumes:
            - type: bind
              source: .
              target: /app
            - type: bind
              source: .container_data
              target: /root
        depends_on:
            - db
            - redis
        ports:
            - "8{{ cookiecutter.id }}:8{{ cookiecutter.id }}"
        working_dir: /app
        command: make django
        tty: true

    celery:
        build: .
        env_file: .env
        environment:
            DATABASE_URL: postgres://{{ cookiecutter.import_name }}:password@db:5432/{{ cookiecutter.import_name }}
            REDIS_URL: redis://redis:6379/0
        volumes:
            - type: bind
              source: .
              target: /app
            - type: bind
              source: .container_data
              target: /root
        depends_on:
            - db
            - redis
        working_dir: /app
        command: make celery
        tty: true

    beat:
        build: .
        env_file: .env
        environment:
            DATABASE_URL: postgres://{{ cookiecutter.import_name }}:password@db:5432/{{ cookiecutter.import_name }}
            REDIS_URL: redis://redis:6379/0
        volumes:
            - type: bind
              source: .
              target: /app
            - type: bind
              source: .container_data
              target: /root
        depends_on:
            - db
            - redis
        working_dir: /app
        command: make beat
        tty: true

    db:
        image: postgres:latest
        ports:
            - "5{{ cookiecutter.id }}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file: .env

    redis:
        image: redis:latest
        ports:
            - "6{{ cookiecutter.id }}:6379"
        volumes:
            - redis_data:/data

networks:
    default:
        name: {{ cookiecutter.import_name }}

volumes:
    postgres_data:
    redis_data:
